AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A small description of the template
Resources:
  UserRoleMappings:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: UsersRoles
      AttributeDefinitions:
      - AttributeName: EntityId
        AttributeType: S
      - AttributeName: Type
        AttributeType: S
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      KeySchema:
      - AttributeName: EntityId
        KeyType: HASH
      - AttributeName: Type
        KeyType: RANGE
