AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: "A small description of the template"

Resources:
  UserRoleMappings:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: UsersRoles
      AttributeDefinitions:
        - AttributeName: PK1A
          AttributeType: S
        - AttributeName: PK1B
          AttributeType: S
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      KeySchema:
        - AttributeName: PK1A
          KeyType: HASH
        - AttributeName: PK1B
          KeyType: RANGE
