AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: >
   The resources for providing a service for listing users and roles.
   It includes a table containing users and roles and lambda functions for accessing the data.


Parameters:
  CognitoAuthorizerArn:
    Type: String



Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      EndpointConfiguration: REGIONAL
      DefinitionUri

  UserRoleMappings:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: UsersRoles
      AttributeDefinitions:
        - AttributeName: PK1A
          AttributeType: S
        - AttributeName: PK1B
          AttributeType: S
      BillingMode: PAY_PER_REQUEST

      KeySchema:
        - AttributeName: PK1A
          KeyType: HASH
        - AttributeName: PK1B
          KeyType: RANGE
